const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

function generateVersion() {
  try {
    let commitCount = 0;
    
    // Attempt 1: Get short SHA if in Vercel (often reliable)
    let commitHash = process.env.VERCEL_GIT_COMMIT_SHA 
      ? process.env.VERCEL_GIT_COMMIT_SHA.substring(0, 7) 
      : '';

    // Attempt 2: If local, try git
    if (!commitHash) {
      try {
        commitHash = execSync('git rev-parse --short HEAD').toString().trim();
      } catch (e) {
        commitHash = 'unknown';
      }
    }

    // Try to get count for local environments
    try {
      commitCount = execSync('git rev-list --count HEAD').toString().trim();
    } catch (e) {
      // If git fails (like in Vercel), we fallback to using the day of the year + hour
      // to create an ever-increasing number for the day
      const now = new Date();
      const start = new Date(now.getFullYear(), 0, 0);
      const diff = now - start;
      const oneDay = 1000 * 60 * 60 * 24;
      const dayOfYear = Math.floor(diff / oneDay);
      // Format: [DayOfYear][Hour] e.g. 6815
      commitCount = `${dayOfYear}${now.getHours()}`;
    }
    
    const versionInfo = {
      version: `v${commitCount}`,
      hash: commitHash,
      timestamp: new Date().toISOString()
    };
    
    const content = `// This file is auto-generated by scripts/generate-version.js
export const APP_VERSION = "${versionInfo.version}";
export const COMMIT_HASH = "${versionInfo.hash}";
export const BUILD_TIMESTAMP = "${versionInfo.timestamp}";
`;

    const filePath = path.join(__dirname, '../src/version.ts');
    fs.writeFileSync(filePath, content);
    console.log('[VERSION] Generated version:', versionInfo.version);
  } catch (error) {
    console.error('[VERSION] Failed to generate version:', error.message);
    const fallbackPath = path.join(__dirname, '../src/version.ts');
    if (!fs.existsSync(fallbackPath)) {
      const fallbackContent = `export const APP_VERSION = "0.0.0-unknown";\nexport const COMMIT_HASH = "unknown";\nexport const BUILD_TIMESTAMP = "${new Date().toISOString()}";\n`;
      fs.writeFileSync(fallbackPath, fallbackContent);
    }
  }
}

generateVersion();
