const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

function generateVersion() {
  try {
    const commitCount = execSync('git rev-list --count HEAD').toString().trim();
    const commitHash = execSync('git rev-parse --short HEAD').toString().trim();
    const pkg = require('../package.json');
    
    const versionInfo = {
      version: `${pkg.version}-${commitCount}`,
      hash: commitHash,
      timestamp: new Date().toISOString()
    };
    
    const content = `// This file is auto-generated by scripts/generate-version.js
export const APP_VERSION = "${versionInfo.version}";
export const COMMIT_HASH = "${versionInfo.hash}";
export const BUILD_TIMESTAMP = "${versionInfo.timestamp}";
`;

    const filePath = path.join(__dirname, '../src/version.ts');
    fs.writeFileSync(filePath, content);
    console.log('[VERSION] Generated version:', versionInfo.version);
  } catch (error) {
    console.error('[VERSION] Failed to generate version:', error.message);
    const fallbackPath = path.join(__dirname, '../src/version.ts');
    if (!fs.existsSync(fallbackPath)) {
      const fallbackContent = `export const APP_VERSION = "0.0.0-unknown";\nexport const COMMIT_HASH = "unknown";\nexport const BUILD_TIMESTAMP = "${new Date().toISOString()}";\n`;
      fs.writeFileSync(fallbackPath, fallbackContent);
    }
  }
}

generateVersion();
