const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

function generateVersion() {
  try {
    const pkg = require('../package.json');
    let commitCount = 0;
    
    try {
      // Intentar descargar el historial completo de git en Vercel para contar bien
      execSync('git fetch --unshallow', { stdio: 'ignore' });
    } catch (e) {
      // Falla silenciosamente si ya tenemos el historial completo o si el entorno no lo permite
    }

    try {
      commitCount = execSync('git rev-list --count HEAD').toString().trim();
    } catch (e) {
      commitCount = "1";
    }
    
    // Formatear a 2 dígitos (ej: "01", "02", "15")
    const formattedCount = String(commitCount).padStart(2, '0');
    
    let commitHash = 'unknown';
    try {
      commitHash = execSync('git rev-parse --short HEAD').toString().trim();
    } catch (e) {}
    
    const versionInfo = {
      version: `v${formattedCount}`,
      hash: commitHash,
      timestamp: new Date().toISOString()
    };
    
    const content = `// This file is auto-generated by scripts/generate-version.js
export const APP_VERSION = "${versionInfo.version}";
export const COMMIT_HASH = "${versionInfo.hash}";
export const BUILD_TIMESTAMP = "${versionInfo.timestamp}";
`;

    const filePath = path.join(__dirname, '../src/version.ts');
    fs.writeFileSync(filePath, content);
    console.log('[VERSION] Generated version:', versionInfo.version);
  } catch (error) {
    console.error('[VERSION] Failed to generate version:', error.message);
    const fallbackPath = path.join(__dirname, '../src/version.ts');
    if (!fs.existsSync(fallbackPath)) {
      const fallbackContent = `export const APP_VERSION = "0.0.0-unknown";\nexport const COMMIT_HASH = "unknown";\nexport const BUILD_TIMESTAMP = "${new Date().toISOString()}";\n`;
      fs.writeFileSync(fallbackPath, fallbackContent);
    }
  }
}

generateVersion();
